# flutter version 3.32.6

name: story_box
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  carousel_slider: ^5.1.1
  blurrycontainer: ^2.1.0
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  fluttertoast: ^8.2.12
  logger: ^2.6.1
  preload_page_view: ^0.2.0
  shimmer: ^3.0.0
  chewie: ^1.12.1
  video_player: ^2.10.0
  readmore: ^3.0.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  http: ^1.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_messaging: ^16.0.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  google_mobile_ads: ^6.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  rate_my_app: ^2.3.2
  shared_preferences: ^2.5.3
  in_app_purchase: ^3.2.3
  flutter_stripe: ^10.0.0
  razorpay_flutter: ^1.4.0
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^19.4.0
  flutter_branch_sdk: ^8.6.0
  dio: ^5.7.0
  share_plus: ^11.0.0
  flutter_bounceable: ^1.2.0
  vibration: ^3.1.3
  flutterwave_standard: ^1.1.0
  loading_animation_widget: ^1.3.0
  clipboard: ^2.0.2
  video_player_android: ^2.8.10
  mobile_device_identifier: ^0.0.3
  no_screenshot: ^0.3.1

  cupertino_icons: ^1.0.8

dependency_overrides:
  dio_web_adapter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
  #    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 800

