module.exports = {
  _id: "6891c8cabe6154302627a96a",
  currency: {
    name: "USD",
    symbol: "$",
    countryCode: "USA",
    currencyCode: "USD",
    isDefault: true,
  },
  storage: {
    awsS3: false,
    digitalOcean: false,
    local: true,
  },
  android: {
    google: {
      interstitial: "android_interstitial_id",
      native: "android_native_id",
      reward: "ca-app-pub-3940256099942544/5224354917",
    },
  },
  ios: {
    google: {
      interstitial: "ios_interstitial_id",
      native: "ios_native_id",
      reward: "ca-app-pub-3940256099942544/1712485313",
    },
  },
  googlePlaySwitch: true,
  stripeSwitch: true,
  stripePublishableKey: "STRIPE_PUBLISHABLE_KEY",
  stripeSecretKey: "STRIPE_SECRET_KEY",
  razorPaySwitch: true,
  razorPayId: "RAZOR PAY ID",
  razorSecretKey: "RAZOR_SECRET_KEY",
  flutterWaveId: "FLUTTER WAVE Id",
  flutterWaveSwitch: true,
  privacyPolicyLink:
    "https://www.termsfeed.com/live/ae4296b0-36ce-4c8d-82ee-8400ae94f581",
  termsOfUsePolicyLink:
    "https://www.termsfeed.com/live/ae4296b0-36ce-4c8d-82ee-8400ae94f581",
  durationOfShorts: 180,
  minCoinForCashOut: 0,
  minWithdrawalRequestedCoin: 0,
  referralRewardCoins: 40,
  watchingVideoRewardCoins: 100,
  commentingRewardCoins: 100,
  likeVideoRewardCoins: 100,
  loginRewardCoins: 5000,
  maxAdPerDay: 6,
  isGoogle: false,
  privateKey: {
    type: "",
    project_id: "",
    private_key_id: "",
    private_key: "",
    client_email: "",
    client_id: "",
    auth_uri: "",
    token_uri: "",
    auth_provider_x509_cert_url: "",
    client_x509_cert_url: "",
    universe_domain: "",
  },
  createdAt: "2024-10-21T11:47:03.908Z",
  updatedAt: "2025-06-13T10:49:15.218Z",
  freeEpisodesForNonVip: 2,
  contactEmail: "support@example.com",
  resendApiKey: "RESEND_API_KEY",
  awsAccessKey: "AWS_ACCESS_KEY",
  awsBucketName: "awsBucketName",
  awsEndpoint: "https://s3.region.amazonaws.com",
  awsHostname: "https://bucket-name.s3.region.amazonaws.com",
  awsRegion: "awsRegion",
  awsSecretKey: "AWS_SECRET_KEY",
  doAccessKey: "DO_ACCESS_KEY",
  doBucketName: "doBucketName",
  doEndpoint: "https://doBucketName.region.digitaloceanspaces.com",
  doHostname: "https://region.digitaloceanspaces.com",
  doRegion: "doRegion",
  doSecretKey: "DO_SECRET_KEY",
};
